TEAM.Name             = "Renegage";
TEAM.Description      = "A member of the Regegades gang.";
TEAM.Color            = Color(220,140,15);
TEAM.Models.Male      = {"models/player/phoenix.mdl"};
TEAM.Models.Female    = TEAM.Models.Male;
TEAM.GroupLevel       = GROUP_GANGMEMBER;
TEAM.PossessiveString = "The %s";
TEAM.SizeLimit        = 10;
TEAM.Salary           = 225;
