TEAM.Name = "Rouge";
TEAM.Description = "A member of the Rouges gang.";
TEAM.Color = Color(220,90,50);
TEAM.Models.Male = {"models/player/guerilla.mdl"};
TEAM.Models.Female = TEAM.Models.Male;
TEAM.GroupLevel = GROUP_GANGMEMBER;
TEAM.PossessiveString = "The %s";
TEAM.SizeLimit = 10;
TEAM.Salary = 225;