--[[
	~ Enums ~
	~ Applejack ~
--]]
-- CLASS_STRING CLASS_LONG CLASS_SHORT CLASS_BOOL CLASS_VECTOR CLASS_ENTITY CLASS_ANGLE CLASS_CHAR CLASS_FLOAT  TYPE_SMALL TYPE_LARGE CAN_TAKE CAN_PUT  OBJ_OWNABLE OBJ_LOCKED OBJ_SEALED  OBJ_PADLOCKED  OBJ_CONTAINER OBJ_INUSE 
CLASS_STRING	= 1;
CLASS_LONG		= 2;
CLASS_SHORT		= 3;
CLASS_BOOL		= 4;
CLASS_VECTOR	= 5;
CLASS_ENTITY	= 6;
CLASS_ANGLE		= 7;
CLASS_CHAR		= 8;
CLASS_FLOAT		= 9;

TYPE_SMALL		= "small"
TYPE_LARGE		= "big"
CAN_TAKE		= 1
CAN_PUT			= 2

--[[ OBJ enums for ent:GetDTInt(3) ]]--
OBJ_OWNABLE		= 1;
OBJ_LOCKED		= 2;
OBJ_SEALED		= 4;

OBJ_PADLOCKED	= 8;

OBJ_CONTAINER	= 16;
OBJ_INUSE		= 32;
