TEAM.Name = "Mayor";
TEAM.Description = "Runs the city and directs the police force.";
TEAM.Color = Color(0,0,255);
TEAM.GroupLevel = GROUP_GANGBOSS;
TEAM.Models.Male = {"models/player/breen.mdl"};
TEAM.Models.Female = TEAM.Models.Male;
TEAM.SizeLimit = 1;
TEAM.Salary = 350;
TEAM.PossessiveString = "The %s";